name: full CI

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  LIBC_CI: 1

jobs:
  style_check:
    name: Style check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: sh ./ci/install-rust.sh
      - name: Check style
        run: sh ci/style.sh


  build_channels_omnios:
    permissions:
      contents: read # to fetch code (actions/checkout)

    name: Build Channels on OmniOS (illumos)
    runs-on: ubuntu-latest
    env:
      OS: illumos
    steps:
      - uses: actions/checkout@v4
      - name: Run OmniOS VM
        id: omnios-ci
        uses: vmactions/omnios-vm@v1
        with:
          envs: 'OS'
          usesh: true
          prepare: |
            pkg install build-essential
          run: |
            INSTALL_RUSTUP=1 TOOLCHAIN=nightly sh ci/install-rust.sh
            source "$HOME/.cargo/env"
            sh ci/run.sh x86_64-unknown-illumos
